name: setup

on:
  push:
    branches:
      - setup
    # paths:
    #   - ingredients/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: copy compose file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          port: 22
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "mattermost-docker/app/Dockerfile"
          target: "~"

      - name: Install Docker && Docker compose
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf volumes/

            ls -a
            sudo yum remove docker -y
            sudo yum update
            sudo amazon-linux-extras install docker
            sudo service docker start

            sudo usermod -a -G docker ec2-user

            sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            mkdir -p ./volumes/app/mattermost/{data,logs,config,plugins,client-plugins}

          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          user: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}

      - name: Fry things up
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
            docker-compose build 
            docker-compose up -d

          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          user: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
