name: setup

on:
  push:
    branches:
      - setup
    # paths:
    #   - ingredients/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Build and push Docker images
      #   uses: docker/build-push-action@v1
      #   with:
      #     path: app
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: anyungu/matter
      #     tags: latest

      - name: copy compose file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          username: ${{ secrets.REMOTE_SERVER_USER }}
          port: 22
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "dock"

      - name: Install Docker && Docker compose
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
            sudo yum remove docker -y
            sudo yum update
            sudo amazon-linux-extras install docker
            sudo service docker start

            sudo usermod -a -G docker ec2-user

            sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose




            mkdir -pv ./volumes/app/mattermost/{data,logs,config,plugins,client-plugins}
            sudo chmod 777 -R ./volumes

          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          user: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}

      - name: Fry things up
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
            cd dock
            sudo docker-compose up -d

          host: ${{ secrets.REMOTE_SERVER_IP_OR_DOMAIN }}
          user: ${{ secrets.REMOTE_SERVER_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
